# Generated by Django 5.0.3 on 2024-03-06 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountNo', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=20)),
                ('accountType', models.CharField(choices=[('s', 'saving'), ('c', 'current')], max_length=20)),
            ],
        ),
    ]
