# Generated by Django 5.0.3 on 2024-03-06 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(111111111111), django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
