# Generated by Django 5.0.3 on 2024-03-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_date_joined_remove_account_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='image',
            new_name='profile_image',
        ),
    ]
