# Generated by Django 5.0.3 on 2024-03-10 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_image_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fathers_name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_application', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_type', models.CharField(choices=[('home_loan', 'Home Loan'), ('education_loan', 'Education Loan')], max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('accountNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTransaction', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('debit', models.PositiveIntegerField(default=0)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField()),
                ('accountNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
