# Generated by Django 5.0.3 on 2024-03-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_accountopened_account_fathers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
